[package]
name = "tenebrium-consensus"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
tenebrium-utxo = { path = "../tenebrium-utxo" }
thiserror = "1.0"